users:
    sumire: ENC[AES256_GCM,data:STCRc27I6r9/eWEYe7f7pudZc49hnuYlZ3kv4fdjd+jzuoVBj98N9UG/IfYzijeybBjDnvtep1y8oC8FAcGDYYhjmqF+miUyEg==,iv:/oMpa9Q07ek7BKvq2Y9WiVBryzBHxS85gOm5SORFYp0=,tag:IEvcZyzJNHTX1CX6Vy2haw==,type:str]
porkbun:
    api-key: ENC[AES256_GCM,data:KQmVBJSiAxQoxtAldVkdlZlp/LzwQnN8VT6nQZTKqEs4GGx3Sm2tbpFYmzA3zd3dXfMlNeIVaNdpR/Q/jegpn9nFU5U=,iv:0sxYYetS6mHGBtUHfKbb02TKRDN9psmx1ds8hCoALyg=,tag:XAUq9LKSJHICfLwd/7TJbg==,type:str]
    secret-api-key: ENC[AES256_GCM,data:I6UUayCjpSvR52Il/JD9A8qEI6BOXW1xmfkKOUsXGGN52G9JRxOSfIf83T4mgN+gFuqAvd2Lui7HQ1q8dgbIUMZMu3M=,iv:XTE0wCtsPdj3/ntnFEKZ03FxxySy6NuoxprXiCmLc8k=,tag:vGJVcey0+iLBIYVcmPWZVA==,type:str]
ssh:
    ed25519: ENC[AES256_GCM,data:spBnY207S/aL/tS32HrKsihnBFEnUWownizrtX0b8Ga+R+rfXWXSTNftGHa63eLQbp9FAyVBKVXh/JoV0PA4o1Y+khYr7d6gRvKNlguhcm3Rx7ECjHL/0+u6eddct2rdz7hs+PvHxUFequLrJTIKv5ICwCdDv8nex8WozeAnHHwyAuEpY1XRM9rnFKp/5/TJrWmiGYhj6vRQr/VMwD/CLedyUR+5D0W5m7QHwsj0ZtQL+racPIhq+ysROhfUrQ1kl9MkWNe3N0Jj5+pccIH2aAZuihxwSxwSRmI90e6jeuOEKT/jsDw0IAgntLySD8d+39DN0wAEXR61K19mp5LC2wzyW9WQ8XoVPhHXz5JXt4ipOKYmjSnNjqe/mZSWCFr/F7b/qZeQ7sDS7/3yhwFAGW5SR7omaubltQ6WjbbNg/h7ZP/IhKanNBo+LI8KWAaH9sqGFD+jGtqszEXq49ODktC6AWdVJZcXmAkdHs51zh2yimMNroBaPlggSzdTYe5nW7np8zAbSisCO0IZ2b/5,iv:HDo09+eQFrGEzWBijfu7utQPo4yuqkCyJBFEeDOalWE=,tag:KafxBJx+ePW3bo+J9nv71g==,type:str]
continuwuity:
    registration: ENC[AES256_GCM,data:Sr2eqZP8MRw1lQyAMAiWTpGrJn4gFTbdRxW9Yz37i/c=,iv:iUatWZFxO3MuVNCTKKaj6VnjmJYGQCVhb6Ldu7Z9xMY=,tag:nDJ7HoHrJJ6hE0RlwC529w==,type:str]
    oidc-secret: ENC[AES256_GCM,data:uTUwORl5sKFCHOTAGT0rKmuFuhmu8LH2RP1sO7qx5oY=,iv:ENI+tapL6R5Ea4+bG2L5hZAbEHicSnEinwy8dqhev+g=,tag:xuqmZxHviEXJtDfItEZiJg==,type:str]
livekit:
    matrix-rtc-secret: ENC[AES256_GCM,data:w9coam3mTWYvl06oAWQK/deXeIszoi0Z0bQsmOhJ305Txgv1JnQR0d7HhFs=,iv:qE21Yp03ZLHeScBgLEXMw2QHQUdSMz7G6mBFaybh/pQ=,tag:d18tjqMxujeQJmW8r7bfhQ==,type:str]
    matrix-rtc-key: ENC[AES256_GCM,data:LAnDw+MtiCo5shuQemOl,iv:ipfIuKm5INRTPUHrfYq0XabSwULIVG1NKTztZw4kFoQ=,tag:T6s344mnWodYGfQjf4/rXw==,type:str]
coturn:
    auth-secret: ENC[AES256_GCM,data:qk0DgWMNiINdxhocR+UY7wI1pQBHUYcJK29gtYEcJJlnvaL1I3Nt3fpkYnK4Wv/F7TVmm9Ve6+gBbFevfebFng==,iv:j5bEiBMrTqSFLFJ/R8C/iGikshSHypUY++UZvZaZ40E=,tag:zY0IFbJ6WIBvomS61x1jNA==,type:str]
pocket-id:
    encryption: ENC[AES256_GCM,data:S5PMwsWhs0XMqcNbcKhJ3/CVPMfuX6GIDo5IJCQ6V0gUHdHQNMTP4dMhSQ8Q2SyiADg/pExPsi1sX0xbyAUqNbYiAhAnVFyW8WSD05iwvoU+nCN/wl1TNZvY2sY2L3HpOjMmA7FZfrr3EYn9zA+47ovyu44ZNOt0+/bDVxnz5b4=,iv:W35lfHmH+E5JGhSpmI9fRkf0EAUkolovbAz3z+cAr+M=,tag:mGIhMFvEyP8DOBBfLoJXUw==,type:str]
    api-key: ENC[AES256_GCM,data:2uX50gGKyBlveaMCn3/+AVZyV/tGEwukmFyGDzg417HXRQewW1f4V/MhBqu4DupsJVqHBrqroS3g4FTZeeI9LCow1xFosDmZOlOcF9z5QhkdAlXY8Sh1yE4guTTbpTbVtckWN5MKcePobyUzDaUDDutcTKs8I6NOHJMa8+ti60c=,iv:n5StBiwaKLT1QuC0GgIHzXuxfU6aGDBvVe+juh8dn+8=,tag:tGId8vAicPJFXQOiZilXcQ==,type:str]
mail:
    no-reply@serdexmethylpheni.date: ENC[AES256_GCM,data:MK1NSCLbfikaoMEu7UmhzE9gq7a4NjfhtHvpGLeP6s5TPbIdetOn6V39RzhnXRpIXyW/hdNOQw3W,iv:c/mqXoVecAOIbV3VwEXrPyxp/eQtpvajnNNTysJN8sA=,tag:ESUjHHEW69nzXHrLji9Ugg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWGVpSUtPY0hsYVo3SFN0
            NmRpVjRERmp6cGVjWndRTTJGMUVGZGxRYkM0CjNsM2dEZmFaNThyeVpMRkNwUCto
            Nk55YVNQSUdPMDZianhEQnR5dGFVM28KLS0tIDd6ZmNxYWtNZWl0TkRuZkdmc2FL
            VWU0akVuTXNxdW5uWW1udTN5ZEZKcmcKUMTbqCUJQbFJgz41zAD8A0YxkNOY2szY
            keJLwBjEbsGsBkd8SHJ9NqLBPFShTCbBMM+rHNUv8Kswg7uPjbWb2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12d2u488fyjp496t9676ufn629clsrza8h8wcfvgqql995clxfq6qy6j4hz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbXNxVXZMZXpsNTFobzB4
            dURCRllkVkkrM2NOY1JBNlJyQTVJRTd3RVEwCnNKZjBwM3dweE1WYzAvYW5uUm85
            bW1UZmdRYTd0eDBYOUpVZ3M0WHhzQmcKLS0tIFI0Rk1LWU9xOHA5UkJMeXBjYjRC
            L2o3R08weUJpNFF4M2VqL0Z1VTZwcXMKzJ6sw7gC7jpPzqVQiyAJwCIe1I/n/sMZ
            7A3piQ2SyIXxEP72bgJ13smo5DETFH63muJdcsmuFXo2KubEd9OiLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
    lastmodified: "2026-08-21T18:35:25Z"
    mac: ENC[AES256_GCM,data:iprQ4fsZgIDlZ9BrKkG75IlhgxRczd4jWJ/gQS8hNMc4+LIn6qEd7nl71rwzWHhTK8cguq70zsLXiGJ+Wis3BbibNW5za8z6THKmpvknPm5+P6FlBL7zoqkFCMVwHzE1v8LQIeiU0MUyqyt7wlI3S9VfXKM0gksJE5T/aa3H+BA=,iv:ifSf+jIquNeuDJYHpTFWYHU33mudFrs+dW8pPs3ukuQ=,tag:LhEnkRZqhEivShO8SvvaVA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
