users:
    sumire: ENC[AES256_GCM,data:STCRc27I6r9/eWEYe7f7pudZc49hnuYlZ3kv4fdjd+jzuoVBj98N9UG/IfYzijeybBjDnvtep1y8oC8FAcGDYYhjmqF+miUyEg==,iv:/oMpa9Q07ek7BKvq2Y9WiVBryzBHxS85gOm5SORFYp0=,tag:IEvcZyzJNHTX1CX6Vy2haw==,type:str]
porkbun:
    api-key: ENC[AES256_GCM,data:KQmVBJSiAxQoxtAldVkdlZlp/LzwQnN8VT6nQZTKqEs4GGx3Sm2tbpFYmzA3zd3dXfMlNeIVaNdpR/Q/jegpn9nFU5U=,iv:0sxYYetS6mHGBtUHfKbb02TKRDN9psmx1ds8hCoALyg=,tag:XAUq9LKSJHICfLwd/7TJbg==,type:str]
    secret-api-key: ENC[AES256_GCM,data:I6UUayCjpSvR52Il/JD9A8qEI6BOXW1xmfkKOUsXGGN52G9JRxOSfIf83T4mgN+gFuqAvd2Lui7HQ1q8dgbIUMZMu3M=,iv:XTE0wCtsPdj3/ntnFEKZ03FxxySy6NuoxprXiCmLc8k=,tag:vGJVcey0+iLBIYVcmPWZVA==,type:str]
ssh:
    ed25519: ENC[AES256_GCM,data:spBnY207S/aL/tS32HrKsihnBFEnUWownizrtX0b8Ga+R+rfXWXSTNftGHa63eLQbp9FAyVBKVXh/JoV0PA4o1Y+khYr7d6gRvKNlguhcm3Rx7ECjHL/0+u6eddct2rdz7hs+PvHxUFequLrJTIKv5ICwCdDv8nex8WozeAnHHwyAuEpY1XRM9rnFKp/5/TJrWmiGYhj6vRQr/VMwD/CLedyUR+5D0W5m7QHwsj0ZtQL+racPIhq+ysROhfUrQ1kl9MkWNe3N0Jj5+pccIH2aAZuihxwSxwSRmI90e6jeuOEKT/jsDw0IAgntLySD8d+39DN0wAEXR61K19mp5LC2wzyW9WQ8XoVPhHXz5JXt4ipOKYmjSnNjqe/mZSWCFr/F7b/qZeQ7sDS7/3yhwFAGW5SR7omaubltQ6WjbbNg/h7ZP/IhKanNBo+LI8KWAaH9sqGFD+jGtqszEXq49ODktC6AWdVJZcXmAkdHs51zh2yimMNroBaPlggSzdTYe5nW7np8zAbSisCO0IZ2b/5,iv:HDo09+eQFrGEzWBijfu7utQPo4yuqkCyJBFEeDOalWE=,tag:KafxBJx+ePW3bo+J9nv71g==,type:str]
continuwuity:
    registration: ENC[AES256_GCM,data:Sr2eqZP8MRw1lQyAMAiWTpGrJn4gFTbdRxW9Yz37i/c=,iv:iUatWZFxO3MuVNCTKKaj6VnjmJYGQCVhb6Ldu7Z9xMY=,tag:nDJ7HoHrJJ6hE0RlwC529w==,type:str]
    oidc-secret: ENC[AES256_GCM,data:J6005SS03VEwkhntTALc5cKOPqxh1af8UD2xpWNg//q+BNrVpkzyL5M3yBZJV1Q0wFYHUPxAWJHFfytGArqVfA==,iv:ElTTamGOegTyKQEMMaDn/Y8IFCuhm6J/s9fu8rp/vbg=,tag:irwKLAJ1YMfWkCowFe9Nkg==,type:str]
kanidm:
    admin-password: ENC[AES256_GCM,data:A5KSBnnqViFJ6OhI1NFj391GFeXFW0SHkEjrtELf39K/LT5KNTGPwYQtlSrkQ1RvS0rp75lNoy00EF7Mb30Ing==,iv:Cxr0dDgMhUvSOBSIFukDL/I6W5koQvKymQIY73aNhZ8=,tag:Ok2mtbPsXhbytUOwsOuezw==,type:str]
livekit:
    matrix-rtc-secret: ENC[AES256_GCM,data:w9coam3mTWYvl06oAWQK/deXeIszoi0Z0bQsmOhJ305Txgv1JnQR0d7HhFs=,iv:qE21Yp03ZLHeScBgLEXMw2QHQUdSMz7G6mBFaybh/pQ=,tag:d18tjqMxujeQJmW8r7bfhQ==,type:str]
    matrix-rtc-key: ENC[AES256_GCM,data:LAnDw+MtiCo5shuQemOl,iv:ipfIuKm5INRTPUHrfYq0XabSwULIVG1NKTztZw4kFoQ=,tag:T6s344mnWodYGfQjf4/rXw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWGVpSUtPY0hsYVo3SFN0
            NmRpVjRERmp6cGVjWndRTTJGMUVGZGxRYkM0CjNsM2dEZmFaNThyeVpMRkNwUCto
            Nk55YVNQSUdPMDZianhEQnR5dGFVM28KLS0tIDd6ZmNxYWtNZWl0TkRuZkdmc2FL
            VWU0akVuTXNxdW5uWW1udTN5ZEZKcmcKUMTbqCUJQbFJgz41zAD8A0YxkNOY2szY
            keJLwBjEbsGsBkd8SHJ9NqLBPFShTCbBMM+rHNUv8Kswg7uPjbWb2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12d2u488fyjp496t9676ufn629clsrza8h8wcfvgqql995clxfq6qy6j4hz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbXNxVXZMZXpsNTFobzB4
            dURCRllkVkkrM2NOY1JBNlJyQTVJRTd3RVEwCnNKZjBwM3dweE1WYzAvYW5uUm85
            bW1UZmdRYTd0eDBYOUpVZ3M0WHhzQmcKLS0tIFI0Rk1LWU9xOHA5UkJMeXBjYjRC
            L2o3R08weUJpNFF4M2VqL0Z1VTZwcXMKzJ6sw7gC7jpPzqVQiyAJwCIe1I/n/sMZ
            7A3piQ2SyIXxEP72bgJ13smo5DETFH63muJdcsmuFXo2KubEd9OiLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
    lastmodified: "2026-07-14T14:34:26Z"
    mac: ENC[AES256_GCM,data:tE+WdLbXoRyary8ZfJrlu9YMAQeAl+/2/C8yrZ/Stgee5pjZSn0g8SPSYHFRUKBIlyU26PWRiANUsCRPjPoFIm4lcihYYn/lyAs1aDuJ/IcwxWV5IEglE9sDSpwwS1Afxlbja8y2iB5qBiuR87powsCl52KbdeMqyKyf2WbVXU8=,iv:zMhOYRhP7TE67jyc3eMX0G2G4xct22UJO5xgjzh1AUI=,tag:LAbYTQ4DZHV4IvKRCpR3Ug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
