on:
  pull_request:
  push:
    paths:
      - 'flake.lock'
      - '**/*.nix'
  workflow_call:
  workflow_dispatch:

jobs:
  checks:
    runs-on: native
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Flake checks
        run: nix flake check
