on:
  push:
    branches:
      - main
    paths:
      - 'flake.lock'
      - '{pkgs,lib,homeModules,modules}/**/*.nix'
      - 'configs/thelessone/**/*.nix'
  workflow_dispatch:

jobs:
  build:
    runs-on: native
    outputs:
      generation: ${{ steps.build.outputs.path }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build generation
        id: build
        run: >
          nix build .#nixosConfigurations.thelessone.config.system.build.toplevel

          echo "path=$(readlink -f ./result)" >> $FORGEJO_OUTPUT

  diff:
    runs-on: native
    needs: build
    steps:
      - name: Diff
        run: dix -v /run/current-system "${{ needs.build.outputs.generation }}"

  deployment:
    runs-on: native
    needs: build
    env:
      DEPLOYMENT_KEY_THELESSNAS: ${{ secrets.DEPLOYMENT_KEY_THELESSNAS }}
    steps:
      - name: Check current generation
        id: check-gen
        run: |
          set -x

          CURRENT_GEN="$(readlink /nix/var/nix/profiles/system | grep -oP 'system-\K\d+')"
          echo "previous=$CURRENT_GEN" >> $FORGEJO_OUTPUT

      - name: Kickstart deployment
        env:
          GENERATION_PATH: ${{ needs.build.outputs.generation }}
        run: >
          eval "$(ssh-agent -s)"
            ssh-add <(echo "$DEPLOYMENT_KEY_THELESSNAS")

          ssh -T root@10.0.0.6
          "
          tmux new -d -s remote-switch-thelessone-local
          '
          rm -rf ./infra
            git clone https://git.theless.one/nanoyaki/infra.git

          eval "$(ssh-agent -s)"
            ssh-add /root/.ssh/id_thelessone_deployment

          nh os switch ./infra
          -H thelessone
          --build-host root@10.0.0.5
          --target-host root@10.0.0.5
          --no-nom -R
          '
          "

      - name: Wait for deployment
        continue-on-error: true
        run: >
          inotifywait
          -e create,delete,move
          -r
          --include '^system-\d+-link$'
          -t 300
          /nix/var/nix/profiles

          sleep 1

      - name: Check generation deployed
        env:
          PREVIOUS_GEN: ${{ steps.check-gen.outputs.previous }}
        run: |
          set -x

          CURRENT_GEN="$(readlink /nix/var/nix/profiles/system | grep -oP 'system-\K\d+')"
          [[ "$CURRENT_GEN" == "$((PREVIOUS_GEN + 1))" ]] || exit 1
