on:
  schedule:
    - cron: '0 2 * * *' # 4 AM
  workflow_dispatch:

# Not implemented yet, keep for the future
permissions:
  pull-requests: write

env:
  NIX_CONFIG: |
    experimental-features = nix-command flakes
    access-tokens = github.com=${{ secrets.HUBGIT_TOKEN }}

jobs:
  update:
    runs-on: nix
    if: forge.ref == 'refs/heads/main' || forge.event_name != 'workflow_dispatch'
    steps:
      - name: Install dependencies
        run: nix profile install nixpkgs#nodejs nixpkgs#tea

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout branch
        run: git checkout -b chore/auto-update

      - name: Setup git
        uses: https://git.theless.one/actions/configure-git@v1
        with:
          username: forgejo[bot]
          email: git@theless.one

      - name: Update flake
        run: nix flake update --commit-lock-file

      - name: Push commit
        run: git push -u origin chore/auto-update -f

      - name: Create Forgejo Pull Request
        uses: https://git.theless.one/actions/create-pr@4a216b0949
        with:
          source-branch: chore/auto-update
          title: 'chore: update flake.lock'
          description: Automated pull request to update flake inputs
          token: ${{ secrets.FORGEJO_BOT_TOKEN }}
          auto-merge: 'true'
