users:
    root: ENC[AES256_GCM,data:GiPBT8BOgOzZ4Kfp20wuSDmVd5aRecMJdK00Yniyk7/kdNkpZeAB2kOUZ+/2AP1FLSs3wi0SrCYS08Pf,iv:d3qhzuh8TSeo82MXeoaU9dD3Dy1bMVZIZrPmgig8FyA=,tag:hmHe0D0Pj+w8qh88QaWhtg==,type:str]
    sentinel: ENC[AES256_GCM,data:rnGVCyP8IEOsQSkCQ7i5BXpK4jBe7Uot54AbebUOPwMX4PNCv7KrWGJ4RDaX+C3MZZCZfVyaLLo7mF/A,iv:fv0pfXMSFOtFmWJmLQe/z0EAQ2j8ZGuoDuVFvaXeuww=,tag:AwsQF1zahiLeNKAp3uz+HQ==,type:str]
wg0: ENC[AES256_GCM,data:X3vPH30Ey+wwkVk+ZSekgH8jr/9fPAmqMmp1ItOMKaACUKPEEVgtVhblWFk=,iv:z0WNqOZoKvm1gNKK6jbO/LROXqByNmWEeo5w0YjBCO8=,tag:k76TFZH0sXDk2I7DQ7uzOw==,type:str]
porkbun:
    api-key: ENC[AES256_GCM,data:UFvblDfDn9gQm3WzbUGUFC2vuIEO9pNtRbrpZkXbF/GrVFeUIQ6M/jJjfHtgaN+zideMvfkISIH+en+ABBJVV9nTKEU=,iv:4L3cLcqhtTbHz3HFtDVWyTh8oSgr5z9Pc1d27fKPqKo=,tag:bzrK2ztMd/qFVYCmZIInJQ==,type:str]
    secret-api-key: ENC[AES256_GCM,data:A4QIDvHyi3HDjVeXA+9QsItUgeD34m2hm1Ep4t2G8DaI7huk8ehLp/lhQWXHMjhrqF73QU9R/Mfx3rysYzK46HHg4ko=,iv:HPiL76h0ySZmSOec+YM8KuDsKlS22shaDxduQ1Qo80E=,tag:zuGxEzF+kj5Bw+kGnhgZog==,type:str]
id_acme_thelessone: ENC[AES256_GCM,data:VxSw0HZirVYw74/XGuxCF/BXjItS5SUHkWT1t31NSkh0BiCqHa+dzmdbHfYaPCY/A6Yg4cYHsdXZZz7We7S0k0e4UvqSXeiH2P4Onn6coKRTwxaucetuZB/zua8Vg2F1mNNDqq10BA1OpQFeY6kzn+aAy1lLRmKprPt7zF4QA0HDqzGL9JRMQyqWsnad+ZJyNWD0R5FpmJC5GpNLSSXot1pgpPEhAxnU+AbAmrl6DzrvRctTG3Dx82feqx0lMGToKpyivKLw0zJ1ilEJiPUJPqTfGEdGMNOQr2q+H0pYrgGzdnK4NWnScQYBkVAWNIC6O8/UF7Mo7MNXwCikSEORkJQIFZUcvx11iHI1dZS+yEWWg1fTCXNpP1nwpyNNuS+nkAYCc4hCQEZLdP0PHDstoa4TKLrP1rVYZnGbHsAF7ZAW754lnEYCXTTjqKlLPhJ2kBatmSdG0kZuaZDlfrqDgSfnBaBp9WFbicic2U0vVmnGVVGoXqe1rxjFD/KWuAUxDRpC,iv:t5eIuY6P86XFSGLCteq+9DVxD7ftlapb0pxDGv5mkhw=,tag:5GS/ojbVMjpY+GvAn3cfNQ==,type:str]
sops:
    age:
        - recipient: age1xqlmklzh0he8xr23wal8kjdhlhqsp8fhvvxqnzn0mkrg2d4ud5ssgq89cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSFlYRHBJZXBlb01zVlp0
            SkZYdUhOeDZjcng3RXd5Wk9yZEVtVW1CQTJrCkNEcFBHcWF4dHQzaFZ5UEROUDdH
            VWpDSXJyblVyUjJwRHNKaDIyYk8wZjQKLS0tICtwOE9VMjNFYTJTaHBhRGsyMDcx
            MjRmeUZvNEs0TENoYnNtWmVhOWdHTWsK8XaDNPtYWL2cJKGhVm26G8E8qWIwSVL6
            LxxlxFGP1KpVoI7S+UoGhT3D71KBlUZpGPaGEnYuZhkwg3LW/o0rXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZi80YzFqcTAvOTBpbjBa
            TU1ab0RNSC96VUh2MmV5cStMZ3JLT1hXRDF3Cm5PMVJwSDBGVVFINTNTbnZvV0Jj
            MUFtZmxTekVXVFNzNjJwZDF5NEpBWGMKLS0tIHFISFBnYlZvNjBIMGZWOXM5TkpI
            d3dwZnZyS1FuRWxpeVBTNzFRZ0pkdGsKZUnIUDii2+OPBNZ6zaK2OYJcc/z/CGXB
            0HizlZWw89z9R8Moz83txvN4xkJHBkxfqlHf7KTnmN3vQXhztCSbzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T21:24:09Z"
    mac: ENC[AES256_GCM,data:g/aMHxJlgTA4sCCDEgob3voLLeU2ueEdtEYpJ+x/YMyw/Rio1Ur7nXykvE/t8PZkefjZK7eaV6OqTXyTkHi5znuIELkGJs1U3VDQ0eoZCTeShViJyWqIZHkPLB/vLJ+Mxhhi5XWi7A+6dAbJdMqqptE4tEFUsyPSKjOZ7z3L0ns=,iv:DdkScumeMpcCOujeMsWn9PQhLhNbeN923z5+hWYwYew=,tag:5uQgyGnlT2ygSlDeG+kodw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
