users:
    root: ENC[AES256_GCM,data:GiPBT8BOgOzZ4Kfp20wuSDmVd5aRecMJdK00Yniyk7/kdNkpZeAB2kOUZ+/2AP1FLSs3wi0SrCYS08Pf,iv:d3qhzuh8TSeo82MXeoaU9dD3Dy1bMVZIZrPmgig8FyA=,tag:hmHe0D0Pj+w8qh88QaWhtg==,type:str]
    sentinel: ENC[AES256_GCM,data:rnGVCyP8IEOsQSkCQ7i5BXpK4jBe7Uot54AbebUOPwMX4PNCv7KrWGJ4RDaX+C3MZZCZfVyaLLo7mF/A,iv:fv0pfXMSFOtFmWJmLQe/z0EAQ2j8ZGuoDuVFvaXeuww=,tag:AwsQF1zahiLeNKAp3uz+HQ==,type:str]
sops:
    age:
        - recipient: age1xqlmklzh0he8xr23wal8kjdhlhqsp8fhvvxqnzn0mkrg2d4ud5ssgq89cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSFlYRHBJZXBlb01zVlp0
            SkZYdUhOeDZjcng3RXd5Wk9yZEVtVW1CQTJrCkNEcFBHcWF4dHQzaFZ5UEROUDdH
            VWpDSXJyblVyUjJwRHNKaDIyYk8wZjQKLS0tICtwOE9VMjNFYTJTaHBhRGsyMDcx
            MjRmeUZvNEs0TENoYnNtWmVhOWdHTWsK8XaDNPtYWL2cJKGhVm26G8E8qWIwSVL6
            LxxlxFGP1KpVoI7S+UoGhT3D71KBlUZpGPaGEnYuZhkwg3LW/o0rXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g76tzmg5pr368e8acvxzlz8rvakzy7atjl0qzm0xsdy56u9m4ejswcss5g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZi80YzFqcTAvOTBpbjBa
            TU1ab0RNSC96VUh2MmV5cStMZ3JLT1hXRDF3Cm5PMVJwSDBGVVFINTNTbnZvV0Jj
            MUFtZmxTekVXVFNzNjJwZDF5NEpBWGMKLS0tIHFISFBnYlZvNjBIMGZWOXM5TkpI
            d3dwZnZyS1FuRWxpeVBTNzFRZ0pkdGsKZUnIUDii2+OPBNZ6zaK2OYJcc/z/CGXB
            0HizlZWw89z9R8Moz83txvN4xkJHBkxfqlHf7KTnmN3vQXhztCSbzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T14:44:09Z"
    mac: ENC[AES256_GCM,data:7RWbno74n1lTTlgCcivYpScd5VZ7m4Yc8/Cs0ivDWn0eB+31Rxbn3E4niDBFdbwB5Wo6IqmX3XkrlfqpgUm/8I5UJ5hn7ZbHORaDDpQ9KZY2ynIOUt0LI5Atd408VvjZei6cpNbF0XLG4VZoJMdtCFmabHqfeFcc9Pd4T8/p8aE=,iv:f8DNwQc/mhX5dAlcvAuyf7q86AyAKyXScVHljurE3/c=,tag:5wNilzG9dX/fNye+RU1YYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
